---
# Source: argo-apps/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx1
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: nginx1
      namespace: dev
    spec:
      project: default
      source:
        repoURL: https://github.com/effip24/devops-aws-infra.git
        targetRevision: HEAD
        path: k8s/charts/main-apps/
        helm:
          valueFiles:
            - values/dev/app1.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
---
# Source: argo-apps/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx2
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: nginx2
      namespace: dev
    spec:
      project: default
      source:
        repoURL: https://github.com/effip24/devops-aws-infra.git
        targetRevision: HEAD
        path: k8s/charts/main-apps/
        helm:
          valueFiles:
            - values/dev/app2.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
---
# Source: argo-apps/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: metrics-server
      namespace: dev
    spec:
      project: default
      source:
        repoURL: metrics-server/metrics-server
        targetRevision: HEAD
        path: k8s/charts/main-apps/
        helm:
          valueFiles:
            - values/dev/app2.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
