---
# Source: argo-apps/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: k8s/charts/main-apps/
    repoURL: https://github.com/effip24/devops-aws-infra.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/dev/app1.yaml
        - values/dev/app2.yaml    
  project: default
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
