---
# Source: argo-apps/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flags
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: k8s/charts/main-app/
    repoURL: https://github.com/effip24/devops-aws-infra.git
    targetRevision: HEAD
  project: default
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: flags
      namespace: dev
    spec:
      project: default
      source:
        repoURL: https://github.com/effip24/devops-aws-infra.git
        targetRevision: HEAD
        path: k8s/charts/main-app/
        helm:
          valueFiles:
            - values/dev/app1.yaml
            - values/dev/app2.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
