server:
  additionalApplications:
    - name: main-app
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/effip24/devops-aws-infra.git
        targetRevision: HEAD
        path: k8s/argocd/applicationsets
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
