apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{ else }}
  name: {{ include "my-charts.fullname" . }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if .Values.service.name }}
      name: {{ .Values.service.name }}
      {{ else }}
      name: http
      {{- end }}
  selector:
    {{- include "my-charts.selectorLabels" . | nindent 4 }}
